### ISSUE TITLE
HA on QNAP - 'HomeAssistant' object has no attribute 'async_create_task'

### ISSUE THREAD

**Issue by Scrappy79** [vincenzosuraci/hassio_meross_sensor_switch#11]
**Home Assistant release with the issue:**
HA 0.93.2

**Last working Home Assistant release (if known):**
Unknown

**Operating environment (Hass.io/Docker/Windows/etc.):**
Qnap (Docker)

**Description of problem:**
After installing meross component following the developer instructions and restarting HA, I get the following error:

```
2019-05-30 13:18:42 DEBUG (MainThread) [meross_init] async_setup() >>> STARTED
2019-05-30 13:18:44 ERROR (MainThread) [homeassistant.setup] Error during setup of component meross
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/setup.py", line 142, in _async_setup_component
    result = await component.async_setup(hass, processed_config)
  File "/config/custom_components/meross/__init__.py", line 76, in async_setup
    hass.data[DOMAIN] = MerossPlatform(hass, config)
  File "/config/custom_components/meross/__init__.py", line 222, in __init__
    hass.async_create_task(self.async_discover_plugs())
AttributeError: 'HomeAssistant' object has no attribute 'async_create_task'
```

```
meross:
  username: !secret meross_userame
  password: !secret meross_password
  scan_interval: 10
  meross_devices_scan_interval: 900
```

**Comment by vincenzosuraci** [comment]
Hi, It seems that the HA version you have does not support async_create_task method for the HomeAssistant object. This Is really strange behaviour, since this method Is very well documented in the HA developer documentation: [link](https://dev-docs.home-assistant.io/en/master/api/core.html#homeassistant.core.HomeAssistant)... I developed the custom component for Hassio (that is HA for Raspberry), I do not tested on a Qnap NAS, however it is very strange what you get... I'll do some code checking

**Comment by vincenzosuraci** [comment]
Checked: code is correctly working. It seems that there is something wrong with the HA you have in Qnap. Unfortunately I cannot do any test, since I do not own a Qnap. However, You did the right think: Ask to the HA developers why you get this error. Unfortunately they responded It was not their issue. But it is, at least on a Qnap environment. 

VS

**Comment by Scrappy79** [comment]
Thanks for the reply. I´ve updated the original issue on the HA developer page:

https://github.com/home-assistant/home-assistant/issues/24196

**Comment by Scrappy79** [comment]
Ok, here is what happened.

The HA version I had installed was 0.65.5. I though it was the latest because I actually updated it via CLI. However, using containers, looks like it's not the way to upgrade the version.

I reinstalled HA with latest version and now is working properly.

Sorry for the confusion.

**Comment by vincenzosuraci** [comment]
No problem! I'll close this issue. Many thanks for your support.
