### ISSUE TITLE
MSG100

### ISSUE THREAD

**Issue by coolguymatt** [vincenzosuraci/hassio_meross_sensor_switch#4]
I tried my MSG100 (garage door opener) and it doesn't look like it works. Here are the logs in HASSIO. Is this an issue with the merossiot library? I noticed there was a new version Alberto was hoping worked with all devices.

18120167058930261h0134298f13c495 failed to process message because: Unknown/Unsupported namespace/command: Appliance.System.Online
18120167058930261h0134298f13c495 failed to process message because: Unknown/Unsupported namespace/command: Appliance.System.Report
18120167058930261h0134298f13c495 failed to process message because: Unknown/Unsupported namespace/command: Appliance.GarageDoor.State

**Comment by vincenzosuraci** [comment]
I never tested MSG100, since I do not own that device. 

However, it seems that the meross_iot library (on top of which my custom-component works) does not support the MSG100. Indeed, the type of errors you reported from your log:

> 18120167058930261h0134298f13c495 failed to process message because: Unknown/Unsupported namespace/command: Appliance.System.Online
18120167058930261h0134298f13c495 failed to process message because: Unknown/Unsupported namespace/command: Appliance.System.Report
18120167058930261h0134298f13c495 failed to process message because: Unknown/Unsupported namespace/command: Appliance.GarageDoor.State

is an output of the meross_iot library from [Alberto Geniola](https://github.com/albertogeniola/MerossIot).

Unfortunately, we have to wait MSG100 to be integrated in the library to make it work on HA with my custom-component. I suggest to open an issue on the github of [Alberto Geniola](https://github.com/albertogeniola/MerossIot) and support him actively to add your device.

VS

**Comment by coolguymatt** [comment]
That is what I thought the answer would be. Thanks
